name: Release apex version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      files:
        description: 'Files to update with version number'
        type: string
        required: true
        default: 'apex.ts, README.md'
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - name: Update version and readme
        env:
          VERSION: ${{ inputs.version }}
          FILES: ${{ inputs.files }}
        run: |
          deno run --allow-run --allow-env --allow-write --allow-read ./.github/workflows/release.ts
          deno run --allow-run --allow-env --allow-write --allow-read ./.github/workflows/update-readme.ts
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.version }} release
          tagging_message: ${{ inputs.version }}
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          generateReleaseNotes: true
          makeLatest: true

      # - name: Commit and tag
      #   env:
      #     VERSION: ${{ inputs.version }}
      #   run: |
      #     git config --global user.email "team@candle.dev"
      #     git config --global user.name "Release Bot"
      #     git add apex.ts README.md
      #     git commit -am "$VERSION release"
      #     git tag $VERSION
      #     git push --tags
